"""add group_id to exams table

Revision ID: 42be13c04712
Revises: e43b42e18a4f
Create Date: 2026-07-05 14:20:52.063029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42be13c04712'
down_revision: Union[str, Sequence[str], None] = 'e43b42e18a4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('group_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'exams', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.drop_column('exams', 'group_id')
    # ### end Alembic commands ###
